DROP DATABASE IF EXISTS DB_PRIMERA;
CREATE DATABASE IF NOT EXISTS DB_PRIMERA;
USE DB_PRIMERA;
CREATE TABLE IF NOT EXISTS Album(
idAlbum INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
albumName VARCHAR(255),
dateReleased DATETIME
);
CREATE TABLE IF NOT EXISTS Genre(
idGenre INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
genre VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS Artist(
idArtist INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
artistName VARCHAR(255)
);
USE DB_PRIMERA;