USE db_autogenerated;
-- apartado 1
SELECT postalZip as "Código postal",region as "Región", country as "País" FROM db_autogenerated.mytable
;
-- apartado 2
select * from db_autogenerated.mytable
where phone like "(811)%"
;
-- apartado 3
select * from db_autogenerated.mytable
where country in ("Italy","Spain")
;
-- apartado 4
select count(*) from db_autogenerated.mytable
;
-- apartado 5
select postalZip, region, country from db_autogenerated.mytable
where id in (select id from db_autogenerated.mytable where country in ("Germany","Turkey"))
;
-- apartado 6
select max(id), min(id) from db_autogenerated.mytable;
-- apartado 7
select distinct country, count(country) from db_autogenerated.mytable
group by country
;
-- apartado 8
select * from db_autogenerated.mytable
order by postalzip asc
limit 10
;
-- apartado 9 peligro peligro
-- delete from db_autogenerated.mytable where country = "Singapore"
select * from db_autogenerated.mytable where country = "Singapore"
;